"""add mode to interview_session

Revision ID: 137545f39261
Revises: 183fb848ebf6
Create Date: 2026-03-24 21:36:56.025078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137545f39261'
down_revision = '183fb848ebf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_session', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
